package com.metaltravelguide.places.tools;

import com.metaltravelguide.places.enums.Country;
import com.metaltravelguide.places.enums.Type;
import com.metaltravelguide.places.models.entities.*;
import com.metaltravelguide.places.repositories.CommentRepository;
import com.metaltravelguide.places.repositories.PlaceRepository;
import com.metaltravelguide.places.repositories.UserRepository;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;
import java.util.Set;

@Service
public class DataInit implements InitializingBean {
    private final UserRepository userRepository;
    private final PlaceRepository placeRepository;
    private final CommentRepository commentRepository;

    public DataInit(UserRepository userRepository, PlaceRepository placeRepository, CommentRepository commentRepository) {
        this.userRepository = userRepository;
        this.placeRepository = placeRepository;
        this.commentRepository = commentRepository;
    }

    private final List<User> users = Arrays.asList(
            new User("admin@mail.com", new BCryptPasswordEncoder().encode("password"), "admin", Country.BE, List.of("ADMIN")),
            new User("marcelo@mail.com", new BCryptPasswordEncoder().encode("password"),"marcelo", Country.BO),
            new User("fred@mail.com", new BCryptPasswordEncoder().encode("password")),
            new User("dirk@mail.com", new BCryptPasswordEncoder().encode("password"))
    );

    private final List<Place> places = Arrays.asList(
            new Place("Rock Classic Bar", "ChIJvYaIWXjEw0cRqUMbnzYa8tA", new Address("Rue du Marché au Charbon", "55", "1000", "Bruxelles", "Bruxelles-Capital", "BE", 50.8462272, 4.3463995), new Contact("+3225121547", "contact@rockclassic.be", "https://www.rockclassic.be", "https://www.facebook.com/rockclassic.bar.7/", "https://www.instagram.com/rockclassicbarbxl", "https://www.twitter.com/rockclassicbarbxl"), Type.BAR, "The Rock Classic cafe is one of the best venues in the city to enjoy rock music. The cool ambience, lively resident DJs, electrifying music and friendly service will give you a pleasant experience. The bar also organises concerts, performances, and other musical events for rock music lovers.", "assets/images/Rock-Classic-Bxl.png", true, users.get(2), Set.of(users.get(2))),
            new Place("Magasin 4", "ChIJBXybQJDDw0cRAz55t3TeL_I", new Address("Avenue du Port", "51B", "1000", "Bruxelles", "Bruxelles-Capital", "BE", 50.8640572, 4.3476754), new Contact("+3222233474", "info@magasin4.be", "https://www.magasin4.be/", "https://www.facebook.com/Magasin-4-129891540419673/", "https://www.instagram.com/magasin4.be/", "https://twitter.com/magasin4"), Type.CONCERTS, "You want to play at Magasin 4 ? Send us your Cd and a biography at the following adress : Magasin 4, Avenue du Port 51b, Be-1000 Bruxelles or send us a link to your website by E-mail at info@magasin4.be. Magasin4 is a club founded in 1994 dedicated to alternative music: Hardcore, Funk, Punk, Alternative Rock, Ska, Pop, Experimental Musics, Chanson Française, Jazz and a lot of original fusions... Réf: 25 Ta Life, Acid Mothers Temple, Aka Moon, Arkangel, Backyard Babies, Babylon Circus, Bollock Brothers, Caspar Brötzman, Converge, Double Nelson, Dub Trio, Eliot Sharp, Enthroned, Eugene Chadbourne, EyeHateGod, Fishbone, Future Loop Foundation, Jaid Fair & Kramer, Kylesa, Laberinto, Le Bal des Enragés, Legendary Pink Dots, Lenght of Time, Lofofora, Ltno, Ludwig von 88, Lydia Lunch, Mad Professor, Marcel et son Orchestre, Marky Ramone, Mass Hysteria, Melt-Banana, No Means No, NRA,  Oxbow, Parrabellum, Percubaba, Punish Yourself, Ruins, Satanic Surfers, Secret Chiefs 3, Senser, Sonny Vincent, Spaceheads, Subhumans, The Ex, The Saints, The Toasters,Today is The Day, Transport League, Tuxedomoon, Unsane, Voodoo Glow Skulls, Wampas, Watcha, Zeni Geva, Zenzile, Zion Train, Zu... Magasin4 is a place where you can make discoveries. In this logic, the entrance fee is quite affordable. Transport: at 500m of Metro Yser (subway) / at 500m of Noord Station (train) / Buses 14 - 15 -245", "assets/images/Magasin-4.png", true, users.get(2), Set.of(users.get(2))),
            new Place("Ancienne Belgique", "ChIJAwZ-Y3jEw0cRsdp0a1IIh1s", new Address("Boulevard Anspach", "110", "1000", "Bruxelles", "Bruxelles-Capital", "BE", 50.847295, 4.3469248), new Contact("+3225482484", "info@abconcerts.be", "https://www.abconcerts.be", "https://www.facebook.com/AncienneBelgiqueAB/", "https://www.instagram.com/abconcerts/", "https://twitter.com/abconcerts"), Type.CONCERTS, "Ancienne Belgique, a concert venue in the heart of Brussels where the music sounds better with you. Mainstream and Niche. Adventurous and Genre-fluid. Day & night.\n You can visit AB if you have a concert ticket. Want to keep up with all that's new at Ancienne Belgique? visit our website www.abconcerts.be or follow us on Facebook, Instagram, Twitter and TikTok under the name 'abconcerts'. Want to join in the fun? Use the hashtag #abconcerts and become a part of our social network!\n We hope to see you soon at Ancienne Belgique - AB!", "https://www.abconcerts.be/media/cache/ogimage/upload/media/default/ae/37621eb52c2a63e6b05af3bad0d310a7175706e6.jpeg", true, users.get(2), Set.of(users.get(2))),
            new Place("Café Central", "ChIJJUZ5c3jEw0cRZ4PxJ81okI8", new Address("Borgwal", "14", "1000", "Bruxelles", "Bruxelles-Capital", "BE", 50.847753, 4.345611), new Contact("", "wearecafecentral@gmail.com", "https://lecafecentral.com/", "https://www.facebook.com/cafecentral.bxl", "https://www.instagram.com/cafecentralbxl/", "https://twitter.com/Cafe_Central"), Type.BAR, "A must-visit place for many years in Brussels. This place focuses clearly on their musical programme, especially raw, alternative and experimental music. Concerts and DJ sets, on a daily basis. Dancing on Thursday, Friday and Saturday at 11 p.m. There are also film showings on Sundays, ranging from cult classics to contemporary indie films. Check the agenda for rock/metal concerts.", "https://agendabrussels.imgix.net/d10acc18f8cda448ccf16d287fe6368bd8a2c03b.jpg", true, users.get(2), Set.of(users.get(2))),
            new Place("Forest National", "ChIJYS9ToDXEw0cRzqBsAWjGs8s", new Address("Avenue Victor Rousseau", "208", "1190", "Bruxelles", "Bruxelles-Capital", "BE", 50.8101295, 4.3218369), new Contact("+3234006970", "info@forestnational.be", "https://forest-national.be/", "https://www.facebook.com/forestnational.vorstnationaal", "https://www.instagram.com/forestnational/", "https://www.twitter.com/forestnational"), Type.CONCERTS, "Forest National is part of be•at. The story starts with the Sportpaleis and later the Lotto Arena. This is followed by the takeovers of the Ethias Arena and Congrestheater (now the Trixxo Arena and the Trixxo Theater) in Hasselt in January 2012, of Forest National in Brussels in October 2013 and of Stadsschouwburg Antwerpen and Capitole Gent in January 2014. Since April 2019, be•at is part of the international Live Nation Entertainment, which counts more than 200 venues worldwide. Be•at's most recent initiative is the launch of the Proximus Pop-Up Arena in Middelkerke.", "https://www.lavenir.net/resizer/M2Q7o_FLClpNHl1gqw4TGOLfD6Y=/768x512/filters:focal(507x313:517x303)/cloudfront-eu-central-1.images.arcpublishing.com/ipmgroup/AV3YJVJMUBBSLOHHMIRCXINDJI.jpg", true, users.get(2), Set.of(users.get(2))),
            new Place("Muziekcentrum Kinky Star", "ChIJSwM1fzdxw0cR7PjllzbvJdU", new Address("Vlasmarkt", "9", "9000", "Gent", "Vlaams-Gewest", "BE", 51.0558213, 3.7263576), new Contact("+3292234845", "info@kinkystar.com", "http://www.kinkystar.com/", "https://www.facebook.com/MuziekcentrumKinkyStar/", "https://www.instagram.com/muziekcentrumkinkystar/", ""), Type.BAR, "Kinky Star is a non-profit youth and music center promoting alternative genres and young debuting artists. We serve as a meeting point for music lovers, musicians and other artists of any kind.", "http://www.kinkystar.com/img/crowdsurf%20femke.jpeg", true, users.get(3), Set.of(users.get(3))),
            new Place("Rainbow Bar & Grill", "ChIJA_UIdqG-woARGfJUiZu5g2s", new Address("Sunset Blvd", "9015", "","West Hollywood", "California", "US", 34.0908937, -118.3903889), new Contact("+13102784232", "contact@rainbowbarandgrill.com", "https://www.rainbowbarandgrill.com/", "https://www.facebook.com/pages/RAINBOW-BAR-AND-GRILL/196112625090", "https://instagram.com/rainbowbarandgrill", "https://twitter.com/rainbowlive"), Type.BAR, "This iconic bar on the Sunset Strip is both a living museum of metal’s glory days and a still very active hot spot for metal fans and musicians. Since 1973, every great in metal and hard rock has hung out at this delightfully stuck-in-time restaurant and bar. Bands have met and formed between the carpeted lounge areas and the parking lot after shows at nearby venues. Members of Guns N’ Roses and Motley Crue have their own booths. The walls are covered in signed memorabilia. At the patio bar, the corner stool has a plaque and next to it, a full-sized statue of Lemmy: This is where Motörhead’s legendary frontman would sit playing video poker and drinking Jack and Cokes. Upstairs, there’s a raised nook that is often occupied by music V.I.P.s, but if it’s empty, take a look at the wooden sign on its railing. This was the treehouse-like hideaway for the 'Hollywood Vampires', a club formed by Alice Cooper, Keith Moon, John Lennon, Ringo Starr, Harry Nilsson and Micky Dolenz.", "assets/images/Rainbow-Bar-Grill.png", true, users.get(1)),
            new Place("Neseblod Records", "ChIJOzaub_ZuQUYRPrcC1mZh1jw", new Address("Schweigaards Gate", "56", "","Oslo", "Østlandet", "NO", 59.9085014, 10.7677383), new Contact("+4798135278", "neseblod@neseblodrecords.com", "https://neseblodrecords.bigcartel.com/", "https://www.facebook.com/neseblodrecords/", "https://www.instagram.com/neseblod_records_666/", "https://twitter.com/neseblodlabel"), Type.HISTORIC, "As the birthplace of metal’s most notorious subgenre, Norway should top the pilgrimage list of every headbanger. Black metal’s origin point can be traced directly to Neseblod Records, formerly known as Helvete. Norwegian for 'hell', Helvete was run by Øystein Aarseth — Euronymous, the guitarist and founding member for Mayhem. Helvete sold the heaviest albums from around the world, attracting metalheads who created a new scene and formed black metal bands in and around Oslo. (The shop has a big role in this year’s Lords of Chaos film.) You can still find an incredible selection of albums spanning the genres of metal here, both renowned and unheard of, but you’ll also find a ton of rare metal merch and, best of all, the walls are a sort of museum for not-for-sale black metal artifacts such as letters from Euronymous and Darkthrone demos. And don’t forget to head down to the basement and take a photo in front of the iconic “Black Metal” wall where the genre’s pioneers took group photos.", "assets/images/Neseblod-Records.png", true, users.get(0)),
            new Place("Sverd i Fjell", "ChIJ3RV65Y5KOkYRiw81Mxv2FF4", new Address("Madlaveien", "366", "","Stavanger", "Vestlandet", "NO", 59.1386358, 6.4979366), new Contact("+4751859200", "info@regionstavanger.com", "https://www.fjordnorway.com/en/see-and-do/swords-in-rock", "https://www.facebook.com/stavangerkommune/", "https://www.instagram.com/stavangerkommune/", "https://twitter.com/kommunen"), Type.HISTORIC, "Swords in Rock in english, is a commemorative monument located in the Hafrsfjord neighborhood of Madla, a borough of the city of Stavanger which lies in the southwestern part of the large municipality of Stavanger in Rogaland county, Norway.", "assets/images/Sverd-i-Fjell.png", true, users.get(0)),
            new Place("Galleri Fjalar", "ChIJx4oW6qb9PEYRnLMW0aWHUkc", new Address("Bryggen", "37", "5003", "Bergen", "Vestlandet", "NO", 60.3975672, 5.3223606), new Contact("", "galleri.fjalar@outlook.com", "http://www.kristianespedal.com/galleri-fjalar/", "https://www.facebook.com/gallerifjalar/", "https://www.instagram.com/gallerifjalar/", ""), Type.HISTORIC, "Galleri Fjalar is a small art gallery and shop in Bergen, Norway run by Kristian Espedal and Robin Jakobsen. The gallery is centrally located at Bryggen (UNESCO World Heritage site) and is usually open every day.\n In addition to Espedal himself, artists like Alex Rose, Erlend Erichsen, Virginie Hils, Eirik Falckner, Raina Vlaskovska, and Trine Grimm have had their work exhibited at Galleri Fjalar since it opened in May 2018.\n A wide selection of prints by Kristian Espedal (and many other artists) is always available at the gallery.\n There is currently no web store, but you can order prints by e-mail.", "http://www.kristianespedal.com/galleri-fjalar/fjalar_20200918.jpg", true, users.get(0)),
            new Place("The Hellfest Lemmy Statue", "ChIJ3d627mJ1BkgR-VRUHyMZAzw", new Address("Rue du Champ Louet", "1", "Warzone Stage","Clisson", "Pays de la Loire", "FR", 47.0978224, -1.2655573), new Contact("+33251887950", "info@hellfest.fr", "https://www.hellfest.fr/", "https://www.facebook.com/hellfest/", "https://www.instagram.com/hellfestopenair/", "https://twitter.com/hellfestopenair"), Type.HISTORIC, "Making sure that France's Hellfest will always have a Lemmy presence, festival organizers have revealed a new statue for this year's edition that replaces the old one that had been in place. Following the Motorhead frontman's death in 2015, organizers decided to have a sculpture created to honor the musician at their festival, and the initial piece went up six years ago, but had started to suffer some plaster crumbling. The new sculpture was the work of artist Caroline Brisset, who accepted the challenge of making the new Lemmy statue for the Hellfest in Clisson, France. A portion of Lemmy's ashes are enshrined in this monument.", "assets/images/Lemmy-Statue.png", true, users.get(1), Set.of(users.get(1), users.get(2))),
            new Place("The Abyss", "ChIJ56t_TUHzT0YRh9D0Qkrb-80", new Address("Andra Långgatan", "35", "","Göteborg", "Västergötland", "SE", 57.6988917, 11.9425334), new Contact("+46733497587", "", "https://theabyss.se/", "https://www.facebook.com/theabyssgbg/", "https://www.instagram.com/theabyssgbg/", ""), Type.BAR, "Home of At The Gates, Dark Tranquility and In Flames, Gothenburg has its own special place in the landscape of Swedish death metal. Often referred to as 'the Gothenburg sound', this picturesque city lined with cobblestoned streets gave the head-banging world a melodic take and now, whether you like your death metal melodic or not, Gothenburg remains a destination with metal cred. The Abyss is at the center of this reputation. This bar is essentially wallpapered in concert fliers, and actually hosts its own concerts on the regular. Like other metal hubs in other cities, The Abyss is a certified after-show spot and a guaranteed way to bond with metalheads from other countries while you sip beer and eat pizza.", "assets/images/The-Abyss.png", true, users.get(1)),
            new Place("Fantoft Stave Church", "ChIJPX2owAv5PEYRKT4wxfIgFL8", new Address("Fantoftvegen", "38", "","Bergen", "Vestland", "NO", 60.3393057, 5.3511013), new Contact("+4755280710", "post@fantoftstavkirke.no", "https://fantoftstavkirke.no/", "https://www.facebook.com/Fantoft-Stavkirke-116279061789665/", "https://www.instagram.com/fantoft_stavkirke/", ""), Type.HISTORIC, "Fantoft Stave Church in Bergen Norway suffered a terrible fate in April of 1992 when it was burned down by Varg Vikernes, a member of the Norwegian black metal band Mayhem and one-man music project Burzum. The Fantoft Stave Church burning had started the war between Norwegian churches vs black metal in Norway.", "assets/images/Fantoft-Church.png", true, users.get(0)),
            new Place("Crypt of the Wizard", "ChIJjTMOMsEcdkgRoAUABYpIpq4", new Address("Hackney Rd", "246", "E2 7SJ", "Greater London", "London", "GB", 51.5308519, -0.0711718), new Contact("", "charlie@cryptofthewizard.com", "https://www.cryptofthewizard.com/", "https://www.facebook.com/cryptofthewizard", "https://www.instagram.com/cryptofthewizard/", ""), Type.STORE, "This is the most metal record store in London. A new record store has opened in East London and it might be the greatest place ever. Lurking on a high street in East London sits a small, unassuming, black-fronted shop with a gothic title above its door. It might not sound much on paper (or your screen), but it’s a portal into the deepest, darkest recesses of heavy metal. Crypt Of The Wizard is London’s newest record store and the only one 100% dedicated to defending the faith. The soundproofed black walls house a plethora of albums across the wide spectrum of heavy music – from Anvil and Sepultura to Hexvessel and Twisted Sister to Mayhem and Solstafir. There’s even a sofa and coffee machine to chill out and admire your purchases. Dedicated to promoting the best in metal, the store has an abundance of underground records unavailable anywhere else in the city. From self-released tapes to a wealth of Mexican black metal, your craving for new noise will be sated. Crypt Of The Wizard is open 11am - 7pm, Tuesday to Sunday, and can be found at 246 Hackney Road, London.", "assets/images/Crypt-of-the-Wizard.png", true, users.get(1))
            );

    private final List<Comment> comments = Arrays.asList(
            new Comment("The best place to see cover bands in Brussels for free!", users.get(2), places.get(0)),
            new Comment("Great place to see underground metal and punk bands.", users.get(2), places.get(1)),
            new Comment("Nice gig in the heart of LA.", users.get(1), places.get(6)),
            new Comment("Where everything began.", users.get(0), places.get(7)),
            new Comment("A magnificent monument with a breathtaking view.", users.get(0), places.get(8)),
            new Comment("An absolute must, Lemmy is God!", users.get(1), places.get(10)),
            new Comment("What a nice ambient! I really enjoyed partying at this bar and met tons of people.", users.get(1), places.get(11)),
            new Comment("Amazingly beautiful wooden church. People who work here don't like to talk about black metal though. Comprehensible.", users.get(0), places.get(12)),
            new Comment("Small record store with a huge variety of dark music.", users.get(1), places.get(13))
    );
    @Override
    public void afterPropertiesSet() {
        userRepository.saveAll(users);
        placeRepository.saveAll(places);
        commentRepository.saveAll(comments);
    }
}
